// Generated by CoffeeScript 1.4.0
(function (){
  var async, onEnd, rpc, server, socketClient, start, _;

  _ = require('underscore');

  async = require('async');

  rpc = require('./../../src/jsonrpc');

  server = rpc.Server.create();

  server.on('error', function (err){
    return console.log(err);
  });

  server.expose('add', function (args, opts, callback){
    return callback(null, args[0] + args[1]);
  });

  server.listenRaw(8089, 'localhost');

  start = void 0;

  socketClient = rpc.Client.create(8089, 'localhost');

  socketClient.connectSocket(function (err, conn){
    var doCall, _i, _results;
    doCall = function (data, next){
      return conn.call('add', [data, data], next);
    };
    start = new Date();
    return async.forEachLimit((function (){
      _results = [];
      for (_i = 0; _i <= 10000; _i++) { _results.push(_i); }
      return _results;
    }).apply(this), 10, doCall, onEnd);
  });

  onEnd = function (){
    var child, exec;
    console.log('');
    console.log('End in ' + ((new Date()) - start) + 'ms');
    exec = require('child_process').exec;
    child = exec('netstat -putone |grep TIME_WAIT |wc -l', function (error, stdout, stderr){
      if (error) {
        console.error(error);
      }
      console.log('netstat -putone |grep TIME_WAIT |wc -l');
      console.log(stdout);
      return console.error(stderr);
    });
  };

  /*
   End in 922ms
   netstat -putone |grep TIME_WAIT |wc -l
   0
   */

}).call(this);
